### ISSUE TITLE
Unable to limit number of parallel cores during DockerBuild

### ISSUE THREAD

**Issue by blaa** [SoftFever/OrcaSlicer#6596]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Linux

### OS Version

Debian Trixie

### Additional system information

32GB RAM
24 threads on AMD Ryzen 9 5900X 12-Core Processor
xmonad (tilling WM)

Number of cores in CPU is probably a problem.

### Printer

Didn't get to select any

### How to reproduce

1. Try to run any of appimages:
OrcaSlicer_Linux_Ubuntu2404_V2.2.0-dev.AppImage
OrcaSlicer_Linux_V2.1.1.AppImage
OrcaSlicer_Linux_V2.2.0-dev.AppImage
and and up with segmentation fault -> Therefore try compilation

3. LinuxBuild fails and I haven't tried to fix that yet.
4. Currently trying DockerBuild.sh with modifications:
```
+  --memory 18G \
   --build-arg USER=$USER \
   --build-arg UID=$(id -u) \
   --build-arg GID=$(id -g) \
-  --build-arg NCORES=$NCORES \
+  --build-arg NCORES=5 \
   $PROJECT_ROOT
```
6. Yet it still spawns tenths of g++/cc1plus processes taking from 3.5 to 1GB of RAM and my 32GB is too little to build it.

### Actual results

Appimage ends with segmentation fault. Docker ends up with OOM killer activity even if I kill all my other apps.

Doing:
fdm@reactor:~$ ./OrcaSlicer_Linux_V2.2.0-dev.AppImage --appimage-mount
/tmp/.mount_OrcaSlMXgEgx
fdm@reactor:/tmp/.mount_OrcaSlMXgEgx$ gdb ./bin/orca-slicer

Gives:
```
Thread 1 "orcaslicer_main" received signal SIGSEGV, Segmentation fault.
0x000055555751129a in wxMediaCtrl2::wxMediaCtrl2(wxWindow*) ()
(gdb) bt
#0  0x000055555751129a in wxMediaCtrl2::wxMediaCtrl2(wxWindow*) ()
#1  0x000055555748bfa2 in Slic3r::GUI::StatusBasePanel::create_monitoring_page() ()
#2  0x00005555574909e5 in Slic3r::GUI::StatusBasePanel::StatusBasePanel(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&) ()
#3  0x000055555749aa0a in Slic3r::GUI::StatusPanel::StatusPanel(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&) ()
#4  0x0000555556e4857f in Slic3r::GUI::MonitorPanel::init_tabpanel() ()
#5  0x0000555556e48d16 in Slic3r::GUI::MonitorPanel::MonitorPanel(wxWindow*, int, wxPoint const&, wxSize const&, long) ()
#6  0x0000555556bf5016 in Slic3r::GUI::MainFrame::init_tabpanel() ()
#7  0x0000555556bf6366 in Slic3r::GUI::MainFrame::MainFrame() ()
#8  0x0000555556baa650 in Slic3r::GUI::GUI_App::on_init_inner() ()
#9  0x0000555556bab81a in Slic3r::GUI::GUI_App::OnInit() ()
#10 0x0000555559a175d7 in wxEntry(int&, wchar_t**) ()
#11 0x0000555556b6b6ab in Slic3r::GUI::GUI_Run(Slic3r::GUI::GUI_InitParams&) ()
#12 0x0000555555fcb42b in Slic3r::CLI::run(int, char**) ()
#13 0x0000555555ec8de9 in main ()

(gdb) info registers
rax            0x0                 0
rbx            0x55555b97b280      93825097249408
rcx            0x55555d3c1590      93825124799888
rdx            0x3                 3
rsi            0x50                80
rdi            0x7ffff0566ad8      140737225583320
rbp            0x7fffffff60f0      0x7fffffff60f0
rsp            0x7fffffff5ff0      0x7fffffff5ff0
```
But I don't know if that's a valid way of taking strace from appimage

Docker build, during:
```
[86/528] Building CXX object src/slic3r/CMakeFiles/libslic3r_gui.dir/GUI/Widgets/StaticBox.cpp.o
```
I see:
```
VSIZE    RSIZE   PSIZE    VGROW   RGROW   SWAPSZ   RUID      EUID         MEM   CMD       1
 3.1G     2.9G      0B     8.2M    6.9M       0B   root      root          9%   cc1plus
 2.9G     2.6G      0B       0B   -0.8M       0B   root      root          8%   cc1plus
 2.7G     2.4G      0B       0B  628.0K       0B   root      root          8%   cc1plus
 1.3G   626.8M      0B       0B  452.0K       0B   root      root          2%   cc1plus
 1.4G   603.8M      0B       0B   -0.2M       0B   root      root          2%   cc1plus
 1.4G   603.7M      0B       0B   -0.4M       0B   root      root          2%   cc1plus
 1.4G   603.0M      0B       0B   28.0K       0B   root      root          2%   cc1plus
 1.5G   602.9M      0B       0B  728.0K       0B   root      root          2%   cc1plus
 1.5G   592.7M      0B       0B  432.0K       0B   root      root          2%   cc1plus
 1.4G   564.0M      0B       0B  -36.0K       0B   root      root          2%   cc1plus
 1.1G   468.8M      0B       0B  648.0K       0B   root      root          1%   cc1plus
 1.1G   468.1M      0B       0B  692.0K       0B   root      root          1%   cc1plus
 1.1G   460.5M      0B       0B   -1.6M       0B   root      root          1%   cc1plus
 1.1G   455.7M      0B       0B   -0.4M       0B   root      root          1%   cc1plus
 1.1G   452.8M      0B       0B   -0.4M       0B   root      root          1%   cc1plus
 1.1G   448.8M      0B       0B    2.9M       0B   root      root          1%   cc1plus
 1.1G   447.1M      0B       0B   -0.9M       0B   root      root          1%   cc1plus
 1.1G   442.1M      0B       0B   -0.7M       0B   root      root          1%   cc1plus
 1.2G   441.0M      0B       0B   -0.4M       0B   root      root          1%   cc1plus
 1.1G   417.2M      0B       0B   -0.5M       0B   root      root          1%   cc1plus
 1.1G   406.1M      0B       0B  568.0K       0B   root      root          1%   cc1plus
 1.1G   365.1M      0B       0B   -1.4M       0B   root      root          1%   cc1plus
50.5M   190.0M      0B       0B    2.5M       0B   root      root          1%   cc1plus
```

which is more than 5 and takes A LOT OF MEMORY.

### Expected results

Either AppImage works, or docker build builds and works later. ;) Bug is about docker / build system as it's more directly observable.

### Project file & Debug log uploads

Unable to start Orca. Debug logs included with context

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by blaa** [comment]
Workaround for the issue:
```
diff --git a/Dockerfile b/Dockerfile
index 868779b0a..8b140da2d 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -71,11 +71,11 @@ RUN ./BuildLinux.sh -u
 RUN ./BuildLinux.sh -d

 # Build slic3r
-RUN ./BuildLinux.sh -s
+RUN ./BuildLinux.sh -s -1

 # Build AppImage
 ENV container podman
-RUN ./BuildLinux.sh -i
+RUN ./BuildLinux.sh -i -1

 # It's easier to run Orca Slicer as the same username,
 # UID and GID as your workstation.  Since we bind mount
```

But that makes the build unnecessarily slow.

(Still the build worked, and Orca works from Docker!)
